handled curl failure

diff --git a/bin/update50 b/bin/update50
--- a/bin/update50
+++ b/bin/update50
@@ -1,4 +1,8 @@
 #!/bin/bash
 
+set -o pipefail
+
 # curl latest update50 script, passing in any command-line args
-curl -H 'Cache-Control: no-cache' -sL https://cs50.ly/update50 | bash -s $@
+if ! curl --fail --header 'Cache-Control: no-cache' --silent --location https://cs50.ly/update50 | bash -s $@; then
+    echo "Unable to update workspace. Try again in a few minutes!"
+fi
